### ISSUE TITLE
Accessing Scope/rootScope

### ISSUE THREAD

**Issue by barhaleacct** [jimobrien/ngMorph#6]
Afternoon
Not entirely an issue - more a query.

Not sure why I can't access anything in the same scope/rootScope as that in the same controller I use to call the modal?
Only way around it I see is to call a new controller from the modal template?

**Comment by jimobrien** [comment]
At the moment, the workaround you've identified is how you can get around this behavior. The template is compiled using the isolated directive scope of the ng-morph-modal directive. There is definitely an improvement to be made here.

**Comment by barhaleacct** [comment]
Super. Cheers
