### ISSUE TITLE
add version information

### ISSUE THREAD

**Issue by westonganger** [jimobrien/ngMorph#7]
When trying to add this to rails-assets.org components:

angular-morph has no versions defined. Please create an issue in component's repository.

**Comment by westonganger** [comment]
All you need to do is create a release with a version number

**Comment by jimobrien** [comment]
Apologies for not getting to this sooner, it's been a hectic week. I've created a release and verified the package on rails-assets.org:

![image](https://cloud.githubusercontent.com/assets/2935356/4332054/a785ff3e-3fce-11e4-8f89-ff24a643e6e7.png)

It should work now.
